name: Update List
on:
  schedule:
    - cron: "0 17 * * *"
  workflow_dispatch:
jobs:
  update-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        run: |
          cd list/clash/ios_rule_script
          bash action.sh
          cd -
          cd list/clash/domain-list-community
          python3 action.py
          cd -
          cd list/cn_address
          bash action.sh
          cd -
          cd list/iptv
          bash action.sh
          cd -

      - name: Check if there are any changes
        id: verify-diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit to own repository
        if: steps.verify-diff.outputs.changed == 'true'
        run: |
          git config --global user.name 'Lujiang'
          git config --global user.email 'Lujiang0111@gmail.com'
          git commit -am "Automated update list"
          git push
